background {
    monitor =
    path = screenshot
    blur_passes = 3
    blur_size = 8
}

input-field {
    monitor =
    size = 250, 50
    position = 0, -80
    halign = center
    valign = center
    outline_thickness = 2
    dots_center = true
    fade_on_empty = false
    placeholder_text = <span foreground="##B8B5AC">Password...</span>
    font_color = rgb(B8B5AC)
    inner_color = rgb(0B0E14)
    outer_color = rgb(FF8F40)
    check_color = rgb(E6C54C)
    fail_color = rgb(F07178)
    shadow_passes = 2
}

label {
    monitor =
    text = Hi, $USER
    color = rgba(B8B5AC, 1.0)
    font_size = 25
    font_family = JetBrainsMono Nerd Font
    position = 0, 80
    halign = center
    valign = center
}

label {
    monitor =
    text = $TIME
    color = rgba(FF8F40, 1.0)
    font_size = 64
    font_family = JetBrainsMono Nerd Font
    position = 0, 200
    halign = center
    valign = center
}
