{ config, lib, pkgs, host, ... }:

{
  # --- Boot ---
  boot.loader.systemd-boot.enable = lib.mkForce false;   # Lanzaboote replaces systemd-boot install
  boot.loader.systemd-boot.configurationLimit = 15;   # Each UKI is ~50-80MB, keep ESP usage under control
  boot.loader.efi.canTouchEfiVariables = true;
  boot.loader.timeout = 30;   # 30s menu delay for dual-boot drive selection
  boot.lanzaboote = {
    enable = true;
    pkiBundle = "/var/lib/sbctl";   # Secure Boot signing keys (generated by sbctl create-keys)
  };
  boot.kernelPackages = pkgs.linuxPackages_latest;   # Latest kernel for newest hardware support
  boot.kernelParams = lib.mkIf host.nvidia [ "nvidia_drm.fbdev=1" ];   # NVIDIA framebuffer (Wayland)

  # tmpfs on RAM -- faster builds, reduces SSD writes
  boot.tmp.useTmpfs = true;
  boot.tmp.tmpfsSize = host.tmpfsSize;

  # AMD CPU microcode updates -- security and stability patches
  hardware.cpu.amd.updateMicrocode = true;

  # Btrfs -- reduces SSD writes (noatime) and saves space (zstd compression)
  fileSystems."/".options = [ "noatime" "compress=zstd" ];
  fileSystems."/home".options = [ "noatime" "compress=zstd" ];

  # --- GPU ---
  hardware.graphics = {
    enable = true;
    enable32Bit = true;   # Needed for Steam/Proton 32-bit games
  };
  services.xserver.videoDrivers = lib.mkIf host.nvidia [ "nvidia" ];
  hardware.nvidia = lib.mkIf host.nvidia {
    modesetting.enable = true;
    open = true;                       # Open kernel modules -- required for 50-series (Blackwell) and newer
    nvidiaSettings = true;             # nvidia-settings GUI
    package = config.boot.kernelPackages.nvidiaPackages.latest;
  };

  # VA-API hardware video acceleration via NVIDIA
  environment.variables.LIBVA_DRIVER_NAME = lib.mkIf host.nvidia "nvidia";

  # --- Hardware Services ---
  services.fstrim.enable = true;        # Weekly SSD TRIM -- maintains write performance and longevity
  services.smartd.enable = true;        # Monitor SSD/HDD health via SMART -- warns before failure
  services.irqbalance.enable = true;    # Distribute hardware interrupts across CPU cores

  # --- Bluetooth ---
  hardware.bluetooth.enable = true;
  hardware.bluetooth.powerOnBoot = true;
  services.blueman.enable = true;       # Bluetooth GUI manager

  # --- Swap ---
  zramSwap.enable = true;              # Compressed RAM swap -- OOM pressure relief without SSD wear
}
